name: vc_deca_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.2.5+1
  firebase_database: ^1.0.5
  firebase_auth: ^0.6.2+1
  firebase_messaging: ^2.0.3
  firebase_storage: ^1.0.4
  fluro: ^1.3.7
  image_picker: ^0.4.10
  intro_views_flutter: "^2.2.4"
  date_format: ^1.0.5
  flutter_slidable: "^0.4.9"
  progress_indicators: ^0.1.2
  image_cropper: ^0.0.9
  url_launcher: ^4.0.2
  webview_flutter: ^0.0.1+1
  flutter_staggered_grid_view:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - images/alert.png
    - images/events.png
    - images/map.png
    - images/platform.png
    - images/vcdeca_blue.png
    - images/vcdeca_white.png
    - images/logo_blue.png
    - images/logo_white.png
    - images/logo_white_trans.png
    - images/logo_blue_trans.png
    - images/vcdeca_white_trans.png
    - images/vcdeca_blue_trans.png
    - images/marketing.png
    - images/finance.png
    - images/hospitality.png
    - images/entrepreneurship.png
    - images/business.png
    - images/personal-finance.png
    - images/filter.png
    - images/full_black_trans.png
    - images/full_white_trans.png
    - images/skin_vcdeca_blue.png
    - images/skin_vcdeca_white.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
    - family: Product Sans
      fonts:
        - asset: fonts/Product Sans Regular.ttf
        - asset: fonts/Product Sans Bold.ttf
          weight: 700
        - asset: fonts/Product Sans Italic.ttf
          style: italic
        - asset: fonts/Product Sans Bold Italic.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
